#ifndef ERRORS_HOLDER_H
#define ERRORS_HOLDER_H

#define NOT_SUPPORTED_ERROR 0
#define SYNTAX_ERROR 1
#define MEMORY_ALLOCATION_ERROR 2
#define INVALID_INPUT_ERROR 3
#define INVALID_OUTPUT_ERROR 4
#define INVALID_ASSIGNMENT_ERROR 5
#define INVALID_IF_ERROR 6
#define INVALID_FOR_ERROR 7
#define INVALID_STATEMENT_ERROR 8
#define INVALID_VARIABLE_ERROR 9
#define INVALID_TYPE_ERROR 10
#define INVALID_EXPRESSION_ERROR 11
#define INVALID_CONDITION_ERROR 12
#define INVALID_OPERATION_ERROR 13
#define INVALID_OPERATOR_ERROR 14
#define INVALID_VARIABLE_NAME_ERROR 15
#define INVALID_VARIABLE_TYPE_ERROR 16
#define INVALID_VARIABLE_VALUE_ERROR 17
#define INVALID_VARIABLE_COUNT_ERROR 18
#define INVALID_VARIABLES_ERROR 19
#define INVALID_VARIABLES_COUNT_ERROR 20
#define INVALID_VARIABLES_TYPE_ERROR 21
#define DUPILCATE_VARIABLE_ERROR 22
#define INVALID_VARIABLES_VALUE_ERROR 23
#define INVALID_VARIABLES_NAME_ERROR 24
#define TYPE_MISMATCH_ERROR 25
#define DIVIDE_BY_ZERO_ERROR 26
void handleError(int errorCode);

#endif